"""empty message

Revision ID: daf00bd7bd65
Revises: 
Create Date: 2018-07-13 20:04:52.980411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'daf00bd7bd65'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
  # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_episode_feed_id'), 'episode', ['feed_id'], unique=False)
    op.create_index(op.f('ix_feed_url'), 'feed', ['url'], unique=True)
    # ### end Alembic commands ###


def downgrade():
  # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feed_url'), table_name='feed')
    op.drop_index(op.f('ix_episode_feed_id'), table_name='episode')
    # ### end Alembic commands ###
