"""Added enclosures info for episodes

Revision ID: b5adf7fac7ab
Revises: 4251f6c2a939
Create Date: 2018-07-19 00:25:39.920621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5adf7fac7ab'
down_revision = '4251f6c2a939'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('episode', sa.Column('enclosure_is_active', sa.Boolean(), nullable=True))
    op.add_column('episode', sa.Column('enclosure_url', sa.Text(), nullable=True))
    op.create_index(op.f('ix_episode_enclosure_is_active'), 'episode', ['enclosure_is_active'], unique=False)
    # ### end Alembic commands ###

    # Populate column with True
    op.execute("""
        UPDATE episode
        SET enclosure_is_active = 'true'
    """)
    op.alter_column('episode', 'enclosure_is_active', nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_episode_enclosure_is_active'), table_name='episode')
    op.drop_column('episode', 'enclosure_url')
    op.drop_column('episode', 'enclosure_is_active')
    # ### end Alembic commands ###
